[package]
name = "chat_server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
dotenvy = "0.15.7"
env_logger = "0.11.5"
futures = "0.3.30"
log = "0.4.22"
tokio = { version = "1.39.3", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["full"] }
